[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tip_jar = "FSrnXoxwum2k6FnvSPfabjaK883ziQ9sW8FcpepJpKEc"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
